import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';

import MantineProvider from "@/providers/MantineProvider";

export const metadata: Metadata = {
  title: "Weather App - ayPromise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        <MantineProvider>
          {children}
        </MantineProvider>

      </body>
    </html>
  );
}
